#Analyzer
server.port=8081

#Database
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/analyzer
spring.datasource.username=analyzer
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=validate

spring.sql.init.mode=always
spring.sql.init.separator=@@
spring.sql.init.schema-locations=classpath:schema.sql

#KafkaHubEventConsumer
spring.kafka.consumer.hub.bootstrap-servers=localhost:9092
spring.kafka.consumer.hub.group.id=analyzer-hub-group
spring.kafka.consumer.hub.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.hub.value-deserializer=ru.yandex.practicum.kafka.deserializer.HubEventDeserializer
spring.kafka.consumer.hub.enable.auto.commit=false
spring.kafka.consumer.hub.auto.offset.reset=latest

#KafkaSensorSnapshotConsumer
spring.kafka.consumer.sensor.bootstrap-servers=localhost:9092
spring.kafka.consumer.sensor.group.id=analyzer-sensor-group
spring.kafka.consumer.sensor.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.sensor.value-deserializer=ru.yandex.practicum.kafka.deserializer.SensorsSnapshotDeserializer
spring.kafka.consumer.sensor.enable.auto.commit=false
spring.kafka.consumer.sensor.auto.offset.reset=latest

#gRPC Configuration
grpc.client.hub-router.address=static://localhost:59090
grpc.client.hub-router.enableKeepAlive=true
grpc.client.hub-router.keepAliveWithoutCalls=true
grpc.client.hub-router.negotiationType=plaintext

#TelemetryTopics
telemetry.hubs.v1.topic=telemetry.hubs.v1
telemetry.snapshots.v1.topic=telemetry.snapshots.v1



