server:
  port: 0

grpc:
  client:
    hub-router:
      address: static://localhost:59090
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_home
    username: dbuser
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

analyzer:
  kafka:
    event-consumer-config:
      bootstrap.servers: localhost:9092
      group.id: analyzer-hub-group
      key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value.deserializer: ru.yandex.practicum.kafka.deserializer.HubEventDeserializer
      enable.auto.commit: false
      auto.offset.reset: latest

    snapshot-consumer-config:
      bootstrap.servers: localhost:9092
      group.id: analyzer-sensor-group
      key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value.deserializer: ru.yandex.practicum.kafka.deserializer.SensorsSnapshotDeserializer
      enable.auto.commit: false
      auto.offset.reset: latest

telemetry:
  topics:
    sensors: telemetry.sensors.v1
    hubs: telemetry.hubs.v1
    snapshots: telemetry.snapshots.v1